name: Docker-Login-Build-Push
on:
  push:
    branches: [master]
    tags:
      - "v*.*.*"
env:
  DOCKER_HUB_REPO: koch64/first_nginx_image
jobs:
  build_and_push:
    name: Build docker image and push to Docker Hub
    # OS of runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to runner
        uses: actions/checkout@v3
      - name: docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            $DOCKER_HUB_REPO
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
# Currently not working
      - name: Build and push
        id: docker_build 
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
