name: Docker-First-Nginx
on:
  push:
    branches: [master]
    workflow-dispatch:
jobs:
  first-attempt:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Starting"
        - uses: actions/checkout@v2
